RF24Ethernet - TCP/IP over RF24Network: RF24EthernetClass Class Reference
RF24EthernetClass Class Reference
#include <RF24Ethernet.h>
Public Member Functions
RF24EthernetClass (RF24 &_radio, RF24Network &_network, RF24Mesh &_mesh)
RF24EthernetClass ()
void use_device ()
void begin (IP_ADDR myIP, IP_ADDR subnet)
void begin (IPAddress ip)
void begin (IPAddress ip, IPAddress dns)
void begin (IPAddress ip, IPAddress dns, IPAddress gateway)
void begin (IPAddress ip, IPAddress dns, IPAddress gateway, IPAddress subnet)
void set_gateway (IPAddress gwIP)
void listen (uint16_t port)
void setMac (uint16_t address)
void setChannel (uint8_t channel)
int available ()
IPAddress localIP ()
IPAddress subnetMask ()
IPAddress gatewayIP ()
IPAddress dnsServerIP ()
void update ()
Friends
class RF24Server
class RF24Client
class RF24UDP
Detailed Description
Examples
Getting_Started_SimpleClient_Mesh.ino, Getting_Started_SimpleClient_Mesh_DNS.ino, Getting_Started_SimpleServer_Mesh.ino, InteractiveServer_Mesh.ino, SLIP_InteractiveServer.ino, SimpleClient_Mesh.ino, mqtt_basic.ino, and mqtt_basic_2.ino.
Definition at line 106 of file RF24Ethernet.h.
Constructor & Destructor Documentation
RF24EthernetClass() [1/2]
RF24EthernetClass::RF24EthernetClass (RF24 & _radio, RF24Network & _network, RF24Mesh & _mesh)
Constructor to set up the Ethernet layer. Requires the radio and network to be configured by the user this allows users to set custom settings at the radio or network level
Definition at line 34 of file RF24Ethernet.cpp.
RF24EthernetClass() [2/2]
RF24EthernetClass::RF24EthernetClass ()
Basic constructor
Member Function Documentation
use_device()
void RF24EthernetClass::use_device ()
Note
Deprecated, maintained for backwards compatibility with old examples
This function is no longer needed, and does nothing
Definition at line 60 of file RF24Ethernet.cpp.
begin() [1/5]
void RF24EthernetClass::begin (IP_ADDR myIP, IP_ADDR subnet)
Configure the IP address and subnet mask of the node. This is independent of the RF24Network layer, so the IP and subnet only have to conform to standard IP routing rules within your network
Referenced by begin(), begin(), and begin().
begin() [2/5]
void RF24EthernetClass::begin (IPAddress ip)
Configure the IP address and subnet mask of the node. This is independent of the RF24Network layer, so the IP and subnet only have to conform to standard IP routing rules within your network
Definition at line 100 of file RF24Ethernet.cpp.
References begin().
begin() [3/5]
void RF24EthernetClass::begin (IPAddress ip, IPAddress dns)
Definition at line 109 of file RF24Ethernet.cpp.
References begin().
begin() [4/5]
void RF24EthernetClass::begin (IPAddress ip, IPAddress dns, IPAddress gateway)
Definition at line 118 of file RF24Ethernet.cpp.
References begin().
begin() [5/5]
void RF24EthernetClass::begin (IPAddress ip, IPAddress dns, IPAddress gateway, IPAddress subnet)
Definition at line 126 of file RF24Ethernet.cpp.
set_gateway()
void RF24EthernetClass::set_gateway (IPAddress gwIP)
Configure the gateway IP address. This is generally going to be your master node with RF24Network address 00.
Definition at line 164 of file RF24Ethernet.cpp.
References uip_ip_addr.
listen()
void RF24EthernetClass::listen (uint16_t port)
Listen to a specified port - This will likely be changed to closer match the Arduino Ethernet API with server.begin();
Definition at line 173 of file RF24Ethernet.cpp.
setMac()
void RF24EthernetClass::setMac (uint16_t address)
Sets the MAC address of the RF24 module, which is an RF24Network address Specify an Octal address to assign to this node, which will be used as the Ethernet mac address If setting up only a few nodes, use 01 to 05 Please reference the RF24Network documentation for information on setting up a static network RF24Mesh will be integrated to provide this automatically
Definition at line 67 of file RF24Ethernet.cpp.
References uip_seteth_addr.
setChannel()
void RF24EthernetClass::setChannel (uint8_t channel)
Sets the Radio channel/frequency to use (0-127)
Definition at line 90 of file RF24Ethernet.cpp.
available()
int RF24EthernetClass::available ()
Indicates whether data is available.
localIP()
IPAddress RF24EthernetClass::localIP ()
Returns the local IP address
Definition at line 180 of file RF24Ethernet.cpp.
References ip_addr_uip.
subnetMask()
IPAddress RF24EthernetClass::subnetMask ()
Returns the subnet mask
Definition at line 190 of file RF24Ethernet.cpp.
References ip_addr_uip.
gatewayIP()
IPAddress RF24EthernetClass::gatewayIP ()
Returns the gateway IP address
Definition at line 200 of file RF24Ethernet.cpp.
References ip_addr_uip.
dnsServerIP()
IPAddress RF24EthernetClass::dnsServerIP ()
Returns the DNS server IP address
Definition at line 210 of file RF24Ethernet.cpp.
update()
void RF24EthernetClass::update ()
Keeps the TCP/IP stack running & processing incoming data
Definition at line 53 of file RF24Ethernet.cpp.
References Ethernet.
Friends And Related Symbol Documentation
RF24Server
friend class RF24Server friend
Definition at line 224 of file RF24Ethernet.h.
RF24Client
friend class RF24Client friend
Definition at line 225 of file RF24Ethernet.h.
RF24UDP
friend class RF24UDP friend
Definition at line 226 of file RF24Ethernet.h.