name: check code formatting

on:
    push:
        branches: [master, v1.x]
    pull_request:
        branches: [master, v1.x]

jobs:
    check_formatting:
        uses: nRF24/.github/.github/workflows/cpp_lint.yaml@main
        with:
            ignore: 'utility|clock-arch.c|clock-arch.h|Dns.cpp|Dns.h'
            extensions: ino,c,cpp,h
